## name of your github action
name: Branch Name Action

## when will the action trigger
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

## the action script
jobs:
  Validate_Branch:
    name: Validator Branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate Branch
        uses: KinsonDigital/BranchValidator@v1.0.0-preview.4 # Make sure this is the latest version
        with:
          branch-name: "${{ github.ref }}" # The current branch where the workflow is running.
          validation-logic: "equalTo('feature/#-*') && equalTo('bugfix/#-*') && equalTo('hotfix/#-*') && equalTo('release/#-*')"
          trim-from-start: "refs/heads/"
          fail-when-not-valid: true