## name of your github action
name: Branch Name Action

## when will the action trigger
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

## the action script
jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check Branch Name
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const core = require('@actions/core');
            const branchName = context.payload.pull_request.head.ref;
            const regex = /^(feature|bugfix|hotfix|release)\/ECOM-\d+\/[\w\- ]+$/;

            if (!regex.test(branchName)) {
              core.setFailed('Branch name does not match the required format: JIRA-<NUMBER>-<desc>');
            } else {
              console.log('Branch name matches the required format');
            }