## name of your github action
name: Branch Name Action

## when will the action trigger
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

## the action script
jobs:
  validate-branch-name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate Branch Format
        uses: KinsonDigital/BranchValidator@v1.0.0-preview.4
        with:
          branch-name: "${{ github.ref }}"
          trim-from-start: "refs/heads/"
          validation-logic: matches("^(feature|bugfix|hotfix|release)/ECOM-[0-9]+/[A-Za-z0-9 _-]+$")
          fail-when-not-valid: true