## name of your github action
name: Dart Linting Action

## when will the action trigger
on:
  pull_request:
  push:

## the action script
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
      - run: dart --version
      - name: Install packages
        run: dart pub get
      - name: Run Dart Analyzer
        run: dart analyze