## name of your github action
name: PR Title Action

## when will the action trigger
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

## the action script
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: thehanimo/pr-title-checker@v1.4.3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pass_on_octokit_error: false
          configuration_path: .github/pr-title-checker-config.json