name: SonarQube Analysis

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Required for SonarQube analysi

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.35.2
      - run: flutter --version
      - name: Install packages
        run: flutter pub get
      # Add Flutter to PATH
      - name: Add Flutter to PATH
        run: echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
      # Run Flutter analyze
      - name: Analyze code
        run: flutter analyze
      # Run tests and generate coverage
      - name: Run tests
        run: flutter test --coverage
      # Run SonarQube scan
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=youssefmdev22_github_actions
            -Dsonar.sources=lib,pubspec.yaml
            -Dsonar.tests=test
            -Dsonar.dart.analyzer.mode=FLUTTER
      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        continue-on-error: true
